### ISSUE TITLE
haproxy 因为配置使用了 consul dns ,所以需要在consul 后启动

### ISSUE THREAD

**Issue by ss75710541** [Dataman-Cloud/offline-yumrepo#2]
haproxy 因为配置使用了 consul dns ,所以需要在consul 后启动
现在的总是是，haproxy启动不了，keepalived 也会不正常，vip会没有，安装中止

**Comment by xiaods** [comment]
consul启动后，应该加一步检测。

**Comment by ss75710541** [comment]
haproxy 已经不使用consul dns 了，关闭
